use std::path::PathBuf;
use std::time::Duration;
use winlane::clipboard::{ClipboardSettings, History, MAX_HISTORY_BYTES, MAX_ITEM_BYTES, ignored};
use winlane::clipboard_store::Store;

const NOW: u64 = 2_000_000;

#[test]
fn clipboard_deduplicates_exact_content_and_searches_in_copy_order() {
    let settings = ClipboardSettings::default();
    let mut history = History::default();
    history.record("first\n  line", "Editor", NOW, &settings);
    let first = history.entries[0].id;
    history.record("https://example.com/中文", "Browser", NOW + 1, &settings);
    let second = history.entries[0].id;
    history.record("first\n  line", "Other", NOW + 2, &settings);
    assert_eq!(history.matching(""), [first, second]);
    assert_eq!(history.matching(" FIRST other "), [first]);
    assert_eq!(history.matching("中文 browser"), [second]);
    assert_eq!(&*history.get(first).unwrap().text, "first\n  line");
    assert_eq!(history.get(first).unwrap().preview(), "first line");
    history.record("first line", "Editor", NOW + 3, &settings);
    assert_eq!(
        history.entries.len(),
        3,
        "whitespace is significant in pasted text"
    );
    assert!(history.remove(first));
    assert!(!history.remove(first));
}

#[test]
fn clipboard_enforces_time_count_and_memory_limits() {
    let mut settings = ClipboardSettings {
        max_items: 2,
        retention_days: 1,
        ..Default::default()
    };
    let mut history = History::default();
    for (text, time) in [("a", NOW), ("b", NOW + 1), ("c", NOW + 2)] {
        history.record(text, "Editor", time, &settings);
    }
    assert_eq!(
        history
            .entries
            .iter()
            .map(|entry| &*entry.text)
            .collect::<Vec<_>>(),
        ["c", "b"]
    );
    assert!(history.prune(NOW + 86402, &settings));
    assert_eq!(history.entries.len(), 1);
    assert!(!history.record(" \n\t", "", NOW, &settings));
    assert!(!history.record(&"x".repeat(MAX_ITEM_BYTES + 1), "", NOW, &settings));
    settings.enabled = false;
    assert!(!history.record("paused", "", NOW, &settings));
    settings.enabled = true;
    settings.max_items = 1000;
    for n in 0..80 {
        history.record(
            &format!("{n:04}{}", "界".repeat((MAX_ITEM_BYTES - 4) / 3)),
            "Editor",
            NOW + 3 + n,
            &settings,
        );
    }
    assert!(
        history
            .entries
            .iter()
            .map(|entry| entry.text.len())
            .sum::<usize>()
            <= MAX_HISTORY_BYTES
    );
    assert!(history.entries.len() < 80);
    assert!(history.entries[0].preview().chars().count() <= 181);
}

#[test]
fn expired_entries_do_not_consume_the_retained_capacity() {
    let settings = ClipboardSettings {
        max_items: 1,
        retention_days: 1,
        ..Default::default()
    };
    let mut history = History::default();
    history.record("new", "", NOW, &settings);
    let mut old = history.entries[0].clone();
    old.id += 1;
    old.copied_at = 0;
    history.entries.insert(0, old);
    assert!(history.prune(NOW, &settings));
    assert_eq!(history.entries.len(), 1);
    assert_eq!(history.entries[0].copied_at, NOW);
}

#[test]
fn clipboard_file_validation_and_legacy_settings_defaults() {
    let config = winlane::config::Config::from_json("{}").unwrap();
    assert_eq!(config.clipboard, ClipboardSettings::default());
    for (max_items, retention_days) in [(0, 7), (1001, 7), (200, 0), (200, 366)] {
        assert!(
            ClipboardSettings {
                max_items,
                retention_days,
                ..Default::default()
            }
            .validate()
            .is_err()
        );
    }
    let settings = ClipboardSettings::default();
    let mut history = History::default();
    history.record("saved", "Example", NOW, &settings);
    let bytes = serde_json::to_vec(&history).unwrap();
    assert_eq!(
        History::from_json(&bytes, NOW, &settings).unwrap().entries,
        history.entries
    );
    assert!(History::from_json(b"not json", NOW, &settings).is_err());
    history.entries.push(history.entries[0].clone());
    assert!(History::from_json(&serde_json::to_vec(&history).unwrap(), NOW, &settings).is_err());
}

#[test]
fn clipboard_ignores_sensitive_generated_and_nontext_items() {
    for kind in [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ] {
        assert!(ignored(
            &["public.utf8-plain-text".into(), kind.into()],
            "com.example.editor"
        ));
    }
    for id in [
        "com.apple.Passwords",
        "com.apple.keychainaccess",
        "com.1password.1password",
        "com.bitwarden.desktop",
    ] {
        assert!(ignored(&["public.utf8-plain-text".into()], id));
    }
    assert!(!ignored(
        &["public.utf8-plain-text".into()],
        "com.example.editor"
    ));
}

#[test]
fn clipboard_does_not_treat_winlane_in_front_as_the_copy_source() {
    for kind in ["public.png", "public.tiff", "public.utf8-plain-text"] {
        assert!(!ignored(&[kind.into()], "app.windowlane.desktop"));
        for marker in [
            "org.nspasteboard.AutoGeneratedType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
        ] {
            assert!(ignored(
                &[kind.into(), marker.into()],
                "app.windowlane.desktop"
            ));
        }
    }
}

struct Temp(PathBuf);
impl Temp {
    fn new() -> Self {
        static NEXT: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);
        let next = NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
        Self(std::env::temp_dir().join(format!(
                "winlane-clipboard-test-{}-{}-{next}",
                std::process::id(),
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap()
                    .as_nanos()
            )))
    }
    fn path(&self) -> PathBuf {
        self.0.join("history.json")
    }
    fn store(&self, settings: ClipboardSettings) -> Store {
        Store::new(self.path(), NOW, settings)
    }
}
impl Drop for Temp {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}
fn loaded(store: &Store) -> Result<History, String> {
    store.loaded.recv_timeout(Duration::from_secs(5)).unwrap()
}

#[test]
fn clipboard_store_flushes_latest_snapshot_and_reloads_private_files() {
    let temp = Temp::new();
    let settings = ClipboardSettings::default();
    let store = temp.store(settings.clone());
    assert!(loaded(&store).unwrap().entries.is_empty());
    let mut history = History::default();
    for n in 0..20 {
        history.record(&format!("text {n}"), "Example", NOW + n, &settings);
        store.save(Some(history.clone()));
    }
    drop(store);
    let store = temp.store(settings);
    assert_eq!(loaded(&store).unwrap().entries, history.entries);
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        assert_eq!(
            std::fs::metadata(temp.path()).unwrap().permissions().mode() & 0o777,
            0o600
        );
        assert_eq!(
            std::fs::metadata(&temp.0).unwrap().permissions().mode() & 0o777,
            0o700
        );
    }
    store.save(Some(history));
    store.save(None);
    drop(store);
    assert!(
        !temp.path().exists(),
        "clear must win over all queued older saves"
    );
}

#[test]
fn clipboard_store_preserves_corrupt_files_until_explicit_clear() {
    let temp = Temp::new();
    std::fs::create_dir_all(&temp.0).unwrap();
    std::fs::write(temp.path(), b"invalid existing file").unwrap();
    let settings = ClipboardSettings::default();
    let store = temp.store(settings.clone());
    assert!(loaded(&store).is_err());
    let mut history = History::default();
    history.record("new copy", "", NOW, &settings);
    store.save(Some(history.clone()));
    drop(store);
    assert_eq!(
        std::fs::read(temp.path()).unwrap(),
        b"invalid existing file"
    );
    let store = temp.store(settings.clone());
    assert!(loaded(&store).is_err());
    store.save(None);
    store.save(Some(history.clone()));
    drop(store);
    let store = temp.store(settings);
    assert_eq!(
        loaded(&store).unwrap().entries,
        history.entries,
        "coalescing must not discard an explicit clear"
    );
}

#[test]
fn memory_only_mode_removes_disk_history() {
    let temp = Temp::new();
    let settings = ClipboardSettings::default();
    let store = temp.store(settings.clone());
    loaded(&store).unwrap();
    let mut history = History::default();
    history.record("previous copy", "", NOW, &settings);
    store.save(Some(history));
    drop(store);
    let store = temp.store(ClipboardSettings {
        persistent: false,
        ..settings
    });
    assert!(loaded(&store).unwrap().entries.is_empty());
    drop(store);
    assert!(!temp.path().exists());
}

fn image_info(bytes: &[u8]) -> winlane::clipboard::ImageInfo {
    winlane::clipboard::ImageInfo {
        key: winlane::clipboard_assets::digest(bytes),
        format: winlane::clipboard::ImageFormat::Png,
        bytes: bytes.len(),
        width: 256,
        height: 128,
        asset: None,
    }
}
#[test]
fn images_share_mru_retention_and_deduplicate_without_losing_text() {
    let settings = ClipboardSettings {
        max_items: 3,
        ..Default::default()
    };
    let mut history = History::default();
    let image = image_info(b"one image");
    history.record("first text", "Editor", NOW, &settings);
    history.record_image(image.clone(), "Browser", NOW + 1, &settings);
    let id = history.entries[0].id;
    history.record("second text", "Editor", NOW + 2, &settings);
    history.record_image(image, "Browser", NOW + 3, &settings);
    assert_eq!(history.entries.len(), 3);
    assert_eq!(history.entries[0].id, id);
    assert_eq!(history.matching("image browser"), [id]);
    assert_eq!(history.matching("图片 256"), [id]);
    let json = serde_json::to_vec(&history).unwrap();
    assert_eq!(
        History::from_json(&json, NOW + 3, &settings)
            .unwrap()
            .entries,
        history.entries
    );
    let mut invalid = image_info(b"one image");
    invalid.key = "../image".into();
    assert!(!history.record_image(invalid, "", NOW, &settings));
    let mut invalid = image_info(b"two");
    invalid.width = u32::MAX;
    assert!(!history.record_image(invalid, "", NOW, &settings));
    history.record("third text", "Editor", NOW + 4, &settings);
    assert_eq!(history.entries.len(), 3);
    assert!(history.prune(NOW + 86400 * 8, &settings));
    assert!(history.entries.is_empty());
}
#[test]
fn image_disk_budget_drops_oldest_images() {
    let settings = ClipboardSettings::default();
    let mut history = History::default();
    for n in 0..6 {
        let mut image = image_info(&[n]);
        image.bytes = winlane::clipboard::MAX_IMAGE_BYTES;
        assert!(history.record_image(image, "", NOW + u64::from(n), &settings));
    }
    assert_eq!(history.entries.len(), 4);
    assert_eq!(history.entries[0].copied_at, NOW + 5);
}
#[test]
fn images_survive_restart_and_clear_removes_persistent_and_temporary_copies() {
    use winlane::clipboard_assets::image_bytes;
    let temp = Temp::new();
    let settings = ClipboardSettings::default();
    let store = temp.store(settings.clone());
    loaded(&store).unwrap();
    let bytes = include_bytes!("fixtures/clipboard-image.png");
    let mut info = image_info(bytes);
    info.asset = Some(store.files.create(&info, bytes, b"thumbnail").unwrap());
    let temporary = info.asset.as_ref().unwrap().image.clone();
    let mut history = History::default();
    history.record_image(info, "Example", NOW, &settings);
    store.save(Some(history.clone()));
    drop(store);
    drop(history);
    assert!(!temporary.exists());
    let store = temp.store(settings);
    let mut history = loaded(&store).unwrap();
    let info = history.entries[0].image.as_ref().unwrap();
    let permanent = temp.0.join("images").join(info.filename());
    let temporary = info.asset.as_ref().unwrap().image.clone();
    assert_eq!(image_bytes(info).unwrap(), bytes);
    assert!(permanent.exists());
    store.save(None);
    drop(store);
    assert!(!permanent.exists());
    assert_eq!(
        image_bytes(history.entries[0].image.as_ref().unwrap()).unwrap(),
        bytes,
        "turning off persistence keeps session images usable"
    );
    history.entries.clear();
    assert!(!temporary.exists());
}
#[test]
fn deleting_an_image_prunes_its_files_but_keeps_other_entries() {
    let temp = Temp::new();
    let settings = ClipboardSettings::default();
    let store = temp.store(settings.clone());
    loaded(&store).unwrap();
    let bytes = include_bytes!("fixtures/clipboard-image.png");
    let mut info = image_info(bytes);
    info.asset = Some(store.files.create(&info, bytes, b"thumbnail").unwrap());
    let permanent = temp.0.join("images").join(info.filename());
    let mut history = History::default();
    history.record_image(info, "Example", NOW, &settings);
    let id = history.entries[0].id;
    history.record("keep", "Editor", NOW, &settings);
    store.save(Some(history.clone()));
    drop(store);
    assert!(permanent.exists());
    let store = temp.store(settings);
    let _ = loaded(&store).unwrap();
    history.remove(id);
    store.save(Some(history));
    drop(store);
    assert!(!permanent.exists());
    assert!(temp.path().exists());
}

#[test]
#[cfg(unix)]
fn stale_session_cleanup_keeps_active_and_unrelated_directories() {
    let temp = Temp::new();
    std::fs::create_dir_all(&temp.0).unwrap();
    let active = temp
        .0
        .join(format!("winlane-images-{}-1-0", std::process::id()));
    let stale = temp.0.join("winlane-images-2147483647-1-0");
    let unrelated = temp.0.join("other-images-2147483647-1-0");
    for path in [&active, &stale, &unrelated] {
        std::fs::create_dir(path).unwrap();
        std::fs::write(path.join("test"), b"fixture").unwrap();
    }
    winlane::clipboard_assets::cleanup_stale_sessions(&temp.0);
    assert!(active.exists());
    assert!(!stale.exists());
    assert!(unrelated.exists());
}
