pub(crate) mod alias_rules;
pub(crate) mod app_shortcuts;
pub(crate) mod clipboard_settings;
pub(crate) mod controls;
pub(crate) mod material;
pub(crate) mod quicklinks;
pub(crate) mod settings;
pub(crate) mod shortcut;
pub(crate) mod snippets;
