pub(crate) mod alias_rules;
pub(crate) mod app_shortcuts;
pub(crate) mod clipboard_settings;
pub(crate) mod controls;
pub(crate) mod input;
pub(crate) mod input_indicator;
pub(crate) mod keep_awake_indicator;
pub(crate) mod material;
pub(crate) mod quicklinks;
mod rule_list;
pub(crate) mod settings;
pub(crate) mod shortcut;
pub(crate) mod snippets;
pub(crate) mod time_indicator;
