fn verify_clipboard_search(mtm: MainThreadMarker) {
    use winlane::clipboard::ClipboardSettings;
    use crate::clipboard_runtime::{ClipboardRuntime, Observer, now};
    let board = NSPasteboard::pasteboardWithUniqueName();
    let path = std::env::temp_dir().join(format!("winlane-native-clipboard-{}", std::process::id())).join("history.json");
    let settings = ClipboardSettings::default();
    let mut observer = Observer::new(&board);
    let mut history = winlane::clipboard::History::default();
    let put = |text: &str| {
        board.clearContents();
        assert!(board.setString_forType(&NSString::from_str(text), unsafe { NSPasteboardTypeString }));
    };
    let capture = |observer: &mut Observer, history: &mut winlane::clipboard::History, settings: &ClipboardSettings| observer.capture(&board, history, settings, "com.example.editor", "Example Editor", now());
    assert!(!capture(&mut observer, &mut history, &settings));
    put("First test copy");
    assert!(capture(&mut observer, &mut history, &settings));
    assert!(!capture(&mut observer, &mut history, &settings));
    put("protected test content");
    board.setData_forType(Some(&NSData::new()), ns_string!("org.nspasteboard.ConcealedType"));
    assert!(!capture(&mut observer, &mut history, &settings));
    put("generated test content");
    crate::clipboard_runtime::mark_generated(&board);
    assert!(!capture(&mut observer, &mut history, &settings));
    put("while paused");
    let paused = ClipboardSettings { enabled: false, ..settings.clone() };
    assert!(!capture(&mut observer, &mut history, &paused));
    assert!(!capture(&mut observer, &mut history, &settings));
    put(&"x".repeat(winlane::clipboard::MAX_ITEM_BYTES + 1));
    assert!(!capture(&mut observer, &mut history, &settings));
    assert_eq!(history.entries.len(), 1);

    let delegate = Delegate::new(mtm);
    let state = delegate.ivars();
    let mut runtime = ClipboardRuntime::with_board(settings.clone(), board.clone(), path.clone());
    let deadline = Instant::now() + Duration::from_secs(5);
    while runtime.loading {
        assert!(Instant::now() < deadline);
        runtime.poll_storage();
        std::thread::sleep(Duration::from_millis(5));
    }
    runtime.history = history;
    runtime.history.record("https://example.com/notes", "Browser", now(), &settings);
    let recent = runtime.history.entries[0].id;
    state.clipboard.replace(Some(runtime));
    state.catalog_checked.set(Some(Instant::now()));
    state.mode.set(Some(PanelMode::Search));
    state.previous_pid.set(-400);
    state.config.borrow_mut().show_usage_hints = false;
    state.config.borrow_mut().snippets = vec![winlane::snippets::Snippet { id: "test".into(), name: "First".into(), body: "Text".into() }];
    delegate.install_windows(vec![WindowInfo { id: 77, pid: -77, app: "Editor".into(), title: "First".into(), minimized: false }]);
    delegate.sync_displays();
    state.query.replace("first".into());
    delegate.filter();
    assert!(state.clipboard_matches.borrow().is_empty(), "ordinary search excludes history");
    state.query.replace("clipboard".into());
    delegate.filter();
    assert_eq!(delegate.selected_command(), Some(CommandId::Clipboard));
    delegate.activate_selected();
    assert!(delegate.searching_clipboard());
    assert!(state.query.borrow().is_empty());
    assert_eq!(state.previous_pid.get(), -400);
    assert_eq!(delegate.match_count(), 2);
    assert_eq!(delegate.selected_clipboard().unwrap().id, recent);
    assert!(state.matches.borrow().is_empty());
    assert!(state.launch_matches.borrow().is_empty());
    assert!(state.snippet_matches.borrow().is_empty());
    for ui in delegate.panels() {
        assert!(!ui.scope_back.isHidden());
        assert!(!ui.clipboard_actions.isHidden());
        assert_eq!(ui.rows.borrow()[0].title.stringValue().to_string(), "https://example.com/notes");
        assert!(ui.scope_back.frame().origin.x + ui.scope_back.frame().size.width < ui.input.frame().origin.x);
        assert!(ui.input.frame().origin.x + ui.input.frame().size.width < ui.clipboard_actions.frame().origin.x);
        assert!(!ui.panel.isVisible());
    }
    delegate.move_selection(1);
    let selected = delegate.selected_clipboard().unwrap().id;
    state.clipboard.borrow_mut().as_mut().unwrap().history.record("Later copy", "Example", now(), &settings);
    delegate.filter_preserving(Some(SelectedResult::Clipboard(selected)));
    assert_eq!(delegate.selected_clipboard().unwrap().id, selected);
    state.catalog_checked.set(None);
    state.query.replace("browser notes".into());
    delegate.filter();
    delegate.ensure_app_catalog();
    assert!(state.catalog_receiver.borrow().is_none());
    assert_eq!(delegate.match_count(), 1);
    assert_eq!(delegate.selected_clipboard().unwrap().id, recent);
    delegate.delete_clipboard_entry();
    assert!(delegate.selected_clipboard().is_none());
    delegate.activate_selected();
    assert!(delegate.searching_clipboard(), "empty Enter leaves history open");
    state.query.borrow_mut().clear();
    delegate.filter();
    delegate.toggle_mode(0);
    assert!(delegate.searching_clipboard(), "Space belongs to history search");
    state.catalog_checked.set(Some(Instant::now()));
    delegate.cancel_search();
    assert!(!delegate.scoped_search());
    assert_eq!(*state.query.borrow(), "clipboard");
    assert_eq!(delegate.selected_command(), Some(CommandId::Clipboard));
    delegate.activate_selected();
    delegate.clear_clipboard_history();
    assert_eq!(delegate.match_count(), 0);
    assert!(state.clipboard.borrow().as_ref().unwrap().history.entries.is_empty());
    delegate.cancel_search();
    delegate.cancel_search();
    assert_eq!(state.mode.get(), None);
    state.clipboard.take();
    assert!(!path.exists());

    let mut runtime = ClipboardRuntime::with_board(settings.clone(), board.clone(), path.clone());
    runtime.configure(ClipboardSettings { persistent: false, ..settings });
    let deadline = Instant::now() + Duration::from_secs(5);
    while runtime.loading { assert!(Instant::now() < deadline); runtime.poll_storage(); std::thread::sleep(Duration::from_millis(5)); }
    assert!(!runtime.poll_clipboard(), "startup must not read pre-existing clipboard content");
    drop(runtime);
    assert!(!path.exists());
    let _ = std::fs::remove_dir_all(path.parent().unwrap());
    board.clearContents();
    println!("Clipboard checks passed: isolated pasteboard capture, markers, pause, scope isolation, MRU search, deletion, clear and navigation; no real clipboard or application changed.");
}
